CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users 
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegram_users VALUES(?,?,?,?,?)
"""

SELECT_USERS = """
SELECT * FROM telegram_users
"""

CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profiles 
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
BIO CHAR(50),
BIRTH_DAY DATE,
GENDER CHAR(1),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_PROFILE_QUERY = """
INSERT INTO profiles VALUES(?,?,?,?,?,?,?)
"""
SELECT_PROFILE = """
SELECT * FROM profiles WHERE TELEGRAM_ID=?
"""

SELECT_ALL_PROFILES = """
SELECT * FROM profiles p 
WHERE p.TELEGRAM_ID NOT IN (
        SELECT ld.OWNER_TELEGRAM_ID
        FROM like_dislike ld 
        WHERE ld.LIKER_TELEGRAM_ID=?
        AND ld.LIKE_DISLIKE_STATUS IS NOT NULL
)
AND p.TELEGRAM_ID != ?
"""

CREATE_LIKE_DISLIKE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS like_dislike
(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
LIKER_TELEGRAM_ID CHAR(50),
LIKE_DISLIKE_STATUS INTEGER,
UNIQUE (OWNER_TELEGRAM_ID, LIKER_TELEGRAM_ID)
)
"""
INSERT_LIKE_QUERY = """ 
INSERT INTO like_dislike VALUES (?,?,?,?)
"""
SELECT_PROFILE_QUERY = """
SELECT * FROM profiles WHERE TELEGRAM_ID = ?
"""
UPDATE_PROFILE_QUERY = """
UPDATE profiles SET NICKNAME = ?, BIO = ?, BIRTH_DAY = ?, GENDER = ?, PHOTO = ?
WHERE TELEGRAM_ID = ? 
"""
DELETE_PROFILE_QUERY = """
DELETE FROM profiles
WHERE TELEGRAM_ID = ?
"""